version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
    volumes: 
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo:3.2
